### ISSUE TITLE
Typo on ranged filters

### ISSUE THREAD

**Issue by danicatalan** [huridocs/uwazi#1812]
Fiilters should say **From/To** instead of **Form/To.**

![image](https://user-images.githubusercontent.com/6364153/43644811-501affe8-9730-11e8-973c-be214f59a837.png)

**Comment by txau** [comment]
Fixed

**Comment by OzrenMuic** [comment]
@txau this bug is still there:

![image](https://user-images.githubusercontent.com/8134850/69539874-ae721300-0f85-11ea-9d18-b12729584cea.png)

**Comment by konzz** [comment]
Is not, is a matter of local traduction, that instance needs to change that label

**Comment by OzrenMuic** [comment]
It is not. I've tried in few instances by adding metadata in English to the template and default label is 'Form' and not 'From'. 

Please check before closing issue.

**Comment by OzrenMuic** [comment]
It is not. I've tried in few instances by adding metadata in English to the template and default label is 'Form' and not 'From'. 

Please check before closing issue.

**Comment by RafaPolit** [comment]
This should be fixed by translating in the Settings -> Translations -> System section.
