### ISSUE TITLE
not able to setup sync with a new blank stated uwazi

### ISSUE THREAD

**Issue by daneryl** [huridocs/uwazi#2640]
after setting up 2 instances, one blank, ill try to run a sync and some of the entities are not synced, did not debug this yet, but the default template its a later feature than the sync and its the not being synced,  probably sync feature assuming no templates on the target ?

**Comment by RafaPolit** [comment]
Does "blank" means a "blank state" or really "blank" as in no data in the DB?

Ideally, the first sync should sync the default template from the master instance.  What would happen is that you need to delete the one from the other instance by hand?

Yes, this needs checking.

**Comment by daneryl** [comment]
@RafaPolit meaning blank state yes.

**Comment by txau** [comment]
@daneryl was this fixed with https://github.com/huridocs/uwazi/issues/2812

**Comment by daneryl** [comment]
@txau no, this is still an issue, im manually change the database. of the target instance for sync to work
