### ISSUE TITLE
Navigating to a text reference from the entity tree is broken

### ISSUE THREAD

**Issue by txau** [huridocs/uwazi#3016]
Create a text reference between two documents and try to open it from the relationship view:

```
TypeError: doc.get(...) is undefined
main.js line 6501 > eval:82:29
    onDocumentReady PDFView.js:66
    onDocumentReady self-hosted:844
    onDocumentReady Document.js:53
    onDocumentReady self-hosted:844
    componentDidUpdate PDF.js:58
    React 14
    loadDocument PDF.js:90
The above error occurred in the <PDF> component:
    in PDF (created by Document)
    in div (created by Document)
    in div (created by Document)
    in div (created by Document)
```

Moreover, when this is fixed ensure the text reference takes the user to the page/position where the reference is in the document.

**Comment by daneryl** [comment]
i have implemented a hot fix, the issue was that at some point we renamed/moved properties of entities. 

- relationships to relations 
- pdfInfo that now its inside the defaultDoc instead of the entity root.

There is no e2e/integration tests for this feature.

should i include e2e for this on the PR ?
migrating to TS also would have prevented this, should i include TS migration on the PR ?

**Comment by txau** [comment]
@daneryl I'd say yes to both questions. For the e2e it will catch even other stuff related to text references, which is important. Please let's use the puppeteer e2e option. Also maybe take a look to re-renders with low "slowMo" values, just in case we can improve some performance.

**Comment by vasyugan** [comment]
Is this fix in Master? Because in 1.6 it fails differently than in 1.5 but it still fails, see https://github.com/huridocs/uwazi/issues/3061

**Comment by txau** [comment]
@vasyugan yes, this is merged already. Are you running the latest version?

**Comment by vasyugan** [comment]
we are running 1.6. Should I upgrade to master to get the fix?

**Comment by txau** [comment]
@vasyugan yes. I just double checked and the bug is fixed.
